# Generated by Django 2.1.3 on 2022-06-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_method',
            field=models.CharField(blank=True, max_length=20, verbose_name='Upload Method'),
        ),
    ]
