# Generated by Django 2.1.3 on 2022-06-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_auto_20220606_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_method',
            field=models.CharField(max_length=20, verbose_name='Upload Method'),
        ),
    ]
